services:
  - type: web
    name: joy-cho-webhook
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: PORT
        value: "10000" # usually you can leave this, Render overrides automatically
